import pytest
import pandas as pd
from pathlib import Path
from autocutai.math import thresholds
import logging

log = logging.getLogger(__name__)

# Path to the LFS-tracked data file generated by the notebook
MATH_DATA_DIR = Path("data/math")
# IMPORTANT: Update this path to match the actual output of your analysis notebook
SILENCE_ROC_SUMMARY = MATH_DATA_DIR / "silence_roc_v1_summary.csv"

@pytest.mark.skipif(not SILENCE_ROC_SUMMARY.exists(),
                    reason=f"Math summary file not found. Requires analysis notebook run and Git LFS checkout.")
def test_silence_threshold_synchronization():
    """
    FAIL-SAFE: Ensures that thresholds in the source code match the
    empirically derived values from the latest analysis.
    """
    try:
        df = pd.read_csv(SILENCE_ROC_SUMMARY)
    except Exception as e:
        pytest.fail(f"Failed to read ROC summary CSV: {e}")

    # Assuming the CSV has columns: 'version', 'optimal_threshold_db'
    try:
        # Get the latest analysis result
        latest_analysis = df.sort_values(by="version", ascending=False).iloc[0]
        derived_threshold = latest_analysis["optimal_threshold_db"]
    except (KeyError, IndexError) as e:
        pytest.fail(f"Missing expected data or columns in ROC summary CSV: {e}")

    code_threshold = thresholds.AUDIO_RMS_SILENCE_THRESHOLD_DB

    assert code_threshold == pytest.approx(derived_threshold), \
        (f"Threshold MISMATCH! Code: {code_threshold} dBFS, Analysis: {derived_threshold} dBFS. "
         f"Rerun the analysis notebook and commit the updates to both code and data.")

    log.info(f"Threshold synchronization verified: {code_threshold} dBFS.")
