# Step 2: Reconstruct the attractor in 3-D

# 2.1  delay.py – compute first minimum of mutual information
import numpy as np, pandas as pd
from tigramite.independence_tests import GPDC

# This script assumes that 'branches.ns' exists and was generated by ci/1-trace.sh
series = pd.read_csv('branches.ns', header=None)[0].values
mi = [GPDC().get_dependence_measure(series, series, lag=t) for t in range(1,50)]
tau = int(np.argmin(mi)) + 1

print(f"Computed delay (tau): {tau}")

# 2.2  embed.py – build delay coordinates
m = 3                       # fixed for CI speed
embedded = np.array([series[i:i+(m-1)*tau+1:tau] for i in range(len(series)-(m-1)*tau)])
np.savetxt('attractor.txt', embedded)

print("Saved attractor to attractor.txt")
